[2023-05-28T22:19:10.212+0000] {processor.py:157} INFO - Started process (PID=21233) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:19:10.213+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:19:10.214+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:19:10.214+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:19:10.219+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:19:10.217+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:19:10.219+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:19:10.244+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.038 seconds
[2023-05-28T22:19:40.395+0000] {processor.py:157} INFO - Started process (PID=21238) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:19:40.396+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:19:40.396+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:19:40.396+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:19:40.399+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:19:40.398+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:19:40.399+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:19:40.417+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.024 seconds
[2023-05-28T22:20:10.691+0000] {processor.py:157} INFO - Started process (PID=21241) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:20:10.693+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:20:10.693+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:20:10.693+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:20:10.696+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:20:10.695+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:20:10.696+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:20:10.713+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.025 seconds
[2023-05-28T22:20:41.078+0000] {processor.py:157} INFO - Started process (PID=21244) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:20:41.078+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:20:41.079+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:20:41.079+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:20:41.081+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:20:41.081+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:20:41.082+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:20:41.098+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.023 seconds
[2023-05-28T22:21:11.883+0000] {processor.py:157} INFO - Started process (PID=21248) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:21:12.014+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:21:12.015+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:21:12.015+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:21:12.017+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:21:12.017+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:21:12.018+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:21:12.037+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.156 seconds
[2023-05-28T22:21:42.729+0000] {processor.py:157} INFO - Started process (PID=21253) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:21:42.730+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:21:42.730+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:21:42.730+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:21:42.733+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:21:42.732+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:21:42.733+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:21:42.749+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.022 seconds
[2023-05-28T22:22:12.959+0000] {processor.py:157} INFO - Started process (PID=21260) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:22:12.961+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:22:12.962+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:22:12.961+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:22:12.967+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:22:12.966+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:22:12.967+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:22:12.986+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.030 seconds
[2023-05-28T22:22:43.328+0000] {processor.py:157} INFO - Started process (PID=21263) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:22:43.445+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:22:43.446+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:22:43.445+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:22:43.448+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:22:43.448+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:22:43.449+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:22:43.466+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.140 seconds
[2023-05-28T22:23:14.032+0000] {processor.py:157} INFO - Started process (PID=21265) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:23:14.032+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:23:14.033+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:23:14.033+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:23:14.035+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:23:14.035+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:23:14.036+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:23:14.053+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.024 seconds
[2023-05-28T22:23:44.728+0000] {processor.py:157} INFO - Started process (PID=21268) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:23:44.729+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:23:44.730+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:23:44.730+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:23:44.733+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:23:44.732+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:23:44.733+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:23:44.751+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.026 seconds
[2023-05-28T22:24:15.113+0000] {processor.py:157} INFO - Started process (PID=21272) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:24:15.115+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:24:15.115+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:24:15.115+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:24:15.118+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:24:15.117+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:24:15.118+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:24:15.136+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.025 seconds
[2023-05-28T22:24:45.489+0000] {processor.py:157} INFO - Started process (PID=21276) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:24:45.491+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:24:45.491+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:24:45.491+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:24:45.494+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:24:45.493+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:24:45.494+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:24:45.514+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.028 seconds
[2023-05-28T22:25:15.895+0000] {processor.py:157} INFO - Started process (PID=21279) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:25:15.895+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:25:15.896+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:25:15.895+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:25:15.898+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:25:15.897+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:25:15.898+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:25:15.916+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.024 seconds
[2023-05-28T22:25:46.264+0000] {processor.py:157} INFO - Started process (PID=21282) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:25:46.266+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:25:46.266+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:25:46.266+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:25:46.269+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:25:46.268+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-05-28T22:25:46.269+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:25:46.287+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.025 seconds
[2023-05-28T22:34:40.219+0000] {processor.py:157} INFO - Started process (PID=21421) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:34:40.220+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:34:40.221+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:34:40.221+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:34:40.226+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:34:40.225+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 22, in <module>
    start_date = airflow.utils.dates.days_ago(1),
NameError: name 'airflow' is not defined
[2023-05-28T22:34:40.227+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:34:40.245+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.028 seconds
[2023-05-28T22:35:10.375+0000] {processor.py:157} INFO - Started process (PID=21434) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:35:10.376+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:35:10.377+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:10.377+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:35:10.381+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:10.380+0000] {dagbag.py:350} ERROR - Failed to import: /home/cloud_user/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/cloud_user/airflow_env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cloud_user/airflow/dags/mydag.py", line 22, in <module>
    start_date = airflow.utils.dates.days_ago(1),
NameError: name 'airflow' is not defined
[2023-05-28T22:35:10.382+0000] {processor.py:838} WARNING - No viable dags retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:35:10.399+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.026 seconds
[2023-05-28T22:35:30.663+0000] {processor.py:157} INFO - Started process (PID=21438) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:35:30.664+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:35:30.665+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.665+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:35:30.676+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:35:30.798+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.797+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:stock_market_dag
[2023-05-28T22:35:30.809+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.809+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:stock_market_dag
[2023-05-28T22:35:30.818+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.818+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:stock_market_dag
[2023-05-28T22:35:30.818+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.818+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:35:30.968+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.967+0000] {dag.py:2747} INFO - Creating ORM DAG for stock_market_dag
[2023-05-28T22:35:30.977+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:35:30.977+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to 2023-05-27T00:00:00+00:00, run_after=2023-05-27T00:00:00+00:00
[2023-05-28T22:35:31.002+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.341 seconds
[2023-05-28T22:36:01.353+0000] {processor.py:157} INFO - Started process (PID=21441) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:36:01.354+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:36:01.356+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:36:01.356+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:36:01.378+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:36:01.414+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:36:01.413+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:36:01.453+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:36:01.453+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to 2023-05-27T00:00:00+00:00, run_after=2023-05-27T00:00:00+00:00
[2023-05-28T22:36:01.504+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.154 seconds
[2023-05-28T22:36:31.670+0000] {processor.py:157} INFO - Started process (PID=21455) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:36:31.677+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:36:31.677+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:36:31.677+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:36:31.689+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:36:31.713+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:36:31.713+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:36:31.734+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:36:31.733+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to 2023-05-27T00:00:00+00:00, run_after=2023-05-27T00:00:00+00:00
[2023-05-28T22:36:31.755+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.087 seconds
[2023-05-28T22:38:12.293+0000] {processor.py:157} INFO - Started process (PID=21980) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:38:12.306+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:38:12.307+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:38:12.306+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:38:12.313+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:38:12.337+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:38:12.337+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:38:12.355+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:38:12.355+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to None, run_after=None
[2023-05-28T22:38:12.459+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.169 seconds
[2023-05-28T22:39:14.615+0000] {processor.py:157} INFO - Started process (PID=22350) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:39:14.616+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:39:14.617+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:39:14.617+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:39:14.624+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:39:14.647+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:39:14.646+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:39:14.664+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:39:14.663+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to None, run_after=None
[2023-05-28T22:39:14.683+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.070 seconds
[2023-05-28T22:39:44.726+0000] {processor.py:157} INFO - Started process (PID=22364) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:39:44.727+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:39:44.727+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:39:44.727+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:39:44.734+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:39:44.773+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:39:44.773+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:39:44.793+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:39:44.793+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to None, run_after=None
[2023-05-28T22:39:44.814+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.091 seconds
[2023-05-28T22:40:15.258+0000] {processor.py:157} INFO - Started process (PID=22368) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:40:15.259+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:40:15.260+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:40:15.260+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:40:15.267+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:40:15.292+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:40:15.292+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:40:15.311+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:40:15.311+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to None, run_after=None
[2023-05-28T22:40:15.336+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.080 seconds
[2023-05-28T22:40:45.924+0000] {processor.py:157} INFO - Started process (PID=22372) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:40:45.925+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:40:45.925+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:40:45.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:40:45.932+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:40:45.954+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:40:45.954+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:40:45.973+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:40:45.973+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to None, run_after=None
[2023-05-28T22:40:45.993+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.071 seconds
[2023-05-28T22:41:16.057+0000] {processor.py:157} INFO - Started process (PID=22384) to work on /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:41:16.058+0000] {processor.py:826} INFO - Processing file /home/cloud_user/airflow/dags/mydag.py for tasks to queue
[2023-05-28T22:41:16.059+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:41:16.058+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:41:16.065+0000] {processor.py:836} INFO - DAG(s) dict_keys(['stock_market_dag']) retrieved from /home/cloud_user/airflow/dags/mydag.py
[2023-05-28T22:41:16.089+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:41:16.089+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-28T22:41:16.111+0000] {logging_mixin.py:149} INFO - [2023-05-28T22:41:16.111+0000] {dag.py:3486} INFO - Setting next_dagrun for stock_market_dag to None, run_after=None
[2023-05-28T22:41:16.132+0000] {processor.py:179} INFO - Processing /home/cloud_user/airflow/dags/mydag.py took 0.078 seconds
